### ISSUE TITLE
Error: EMFILE: too many open files, open 'c:\Users\belesiu\OneDrive\1-Documents\Zettelkasten_A1\Zettlr_Stress_Test\notes\suety minister plenipotentiary.md'

### ISSUE THREAD

**Issue by belesiu** [uozuAho/note_searcher#6]
I have a directory with over 10000 files and when trying to run note-searcher, it throw the following error:

Error: EMFILE: too many open files, open 'c:\Users\belesiu\OneDrive\1-Documents\Zettelkasten_A1\Zettlr_Stress_Test\notes\suety minister plenipotentiary.md'

**Comment by uozuAho** [comment]
Sorry for the super late response! I haven't got my github notifications worked out. I'll have a go at testing this out soon.

**Comment by uozuAho** [comment]
Fixed in [1.0.1](https://github.com/uozuAho/note_searcher/releases/tag/releases%2F1.0.1). I tested it with https://github.com/Zettelkasten-Method/10000-markdown-files . It takes about 20 seconds to index on my machine, but at least it doesn't get the EMFILE error any more.

Please reopen this issue if it's still giving you trouble!
